#!/usr/bin/env node
// Export the llm-swap provider (models.json) to every harness that can take a
// custom OpenAI-compatible provider. Where a harness has a plugin API the
// provider ships as a real plugin; only the plugin registration or provider
// block is machine config:
//   opencode  ~/.config/opencode/opencode.json  "plugin" entry -> opencode.mjs
//   codex     ~/.codex/config.toml              marker-delimited block (no
//             plugin/provider API exists, config is the only path)
// pi is not handled here - the extension installs as a pi package (see
// install-pi-packages.sh). Claude Code has no custom-provider mechanism.
// Harnesses whose CLI is absent are skipped.
//
//   node install.mjs          merge for the harnesses present on this machine
//   node install.mjs --check  self-test the merge logic, write nothing
import { strict as assert } from "node:assert";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(readFileSync(join(here, "models.json"), "utf8"));
const have = (cli) => spawnSync("sh", ["-c", `command -v ${cli}`]).status === 0;

// --- opencode: register opencode.mjs in the "plugin" array; the plugin's
// config hook injects the provider live.

const PLUGIN_PATH = join(here, "opencode.mjs");

function opencodeMerge(cfg) {
  return { ...cfg, plugin: [...new Set([...(cfg.plugin ?? []), PLUGIN_PATH])] };
}

// --- codex: model_providers is only honored in user-level config.toml, so
// merge a marker-delimited block we own. Never parses the rest of the file.
// ponytail: duplicate [model_providers.llm-swap] outside our markers would
// break the TOML; parse properly if that ever happens.

const BEGIN = "# >>> llm-swap (generated by llm-swap/install.mjs) >>>";
const END = "# <<< llm-swap <<<";

function codexBlock() {
  return [
    BEGIN,
    "[model_providers.llm-swap]",
    'name = "llm-swap"',
    `base_url = "${catalog.baseUrl}"`,
    'wire_api = "chat"',
    END,
    "",
  ].join("\n");
}

function codexMerge(text) {
  const block = codexBlock();
  const start = text.indexOf(BEGIN);
  if (start === -1)
    return text + (text === "" || text.endsWith("\n") ? "" : "\n") + block;
  const end = text.indexOf(END, start);
  if (end === -1) throw new Error("unterminated llm-swap block in config.toml");
  let tail = text.indexOf("\n", end);
  tail = tail === -1 ? text.length : tail + 1;
  return text.slice(0, start) + block + text.slice(tail);
}

// --- self-test ---

if (process.argv.includes("--check")) {
  const oc = opencodeMerge({ theme: "x", plugin: ["some-npm-plugin"] });
  assert.equal(oc.theme, "x");
  assert.deepEqual(oc.plugin, ["some-npm-plugin", PLUGIN_PATH]);
  assert.deepEqual(opencodeMerge(oc), oc); // idempotent

  const fresh = codexMerge("");
  assert.ok(fresh.includes("[model_providers.llm-swap]"));
  assert.equal(codexMerge(fresh), fresh); // idempotent
  const mid = codexMerge(`model = "gpt-5"\n${fresh}[foo]\nbar = 1\n`);
  assert.ok(mid.startsWith('model = "gpt-5"\n'));
  assert.ok(mid.endsWith("[foo]\nbar = 1\n"));
  assert.equal((mid.match(/model_providers\.llm-swap/g) ?? []).length, 1);
  console.log("llm-swap: install.mjs check ok");
  process.exit(0);
}

// --- merge for present harnesses ---

if (have("opencode")) {
  const cfgPath = join(
    process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config"),
    "opencode",
    "opencode.json",
  );
  const cfg = existsSync(cfgPath)
    ? JSON.parse(readFileSync(cfgPath, "utf8"))
    : { $schema: "https://opencode.ai/config.json" };
  mkdirSync(dirname(cfgPath), { recursive: true });
  writeFileSync(cfgPath, JSON.stringify(opencodeMerge(cfg), null, 2) + "\n");
  console.log(`llm-swap: opencode plugin registered in ${cfgPath}`);
} else {
  console.log("llm-swap: opencode not found, skipped");
}

if (have("codex")) {
  const cfgPath = join(process.env.CODEX_HOME ?? join(homedir(), ".codex"), "config.toml");
  mkdirSync(dirname(cfgPath), { recursive: true });
  writeFileSync(cfgPath, codexMerge(existsSync(cfgPath) ? readFileSync(cfgPath, "utf8") : ""));
  console.log(`llm-swap: codex provider merged into ${cfgPath} (pick models with codex -c model_provider=llm-swap -m <id>)`);
} else {
  console.log("llm-swap: codex not found, skipped");
}
